### PR TITLE
Moved INFO to the database

### PR DESCRIPTION
**Pull request by thatandyrose**
- Ability to create/update users
- Info is now in the User Model
- User gets redirect to new_user_path if no user exists
- Fixed bug with errors message in Users form
- Added Thin
- There was a bunch of other commits, but I reverted them all

### CODE REVIEW

**Comment by thatandyrose** [comment]
Hey @natew would love to contribute and really make this a kickass and easy to use blogging engine.

**Comment by natew** [comment]
I'd love for some help on this, but I definitely can't accept this as a pull request.  Ideally pull requests should be focused on one fix or improvement, and should have a clean history of commits (no reverts, etc).

If you'd like I think you have a few pull requests but you'd need to start from a clean branch of master.  Checkout the master branch from github and then create a new branch for each fix.  Once you've committed the changes, go ahead and submit me a pull request and we can go from there.

I think the typekit removal, better instructions, and style tweaks could be three pull requests.

Thanks!

**Comment by natew** [comment]
Check out my comment on github.

On Fri, Oct 4, 2013 at 7:00 AM, Andy notifications@github.com wrote:

> Hey @natew https://github.com/natew would love to contribute and really
> make this a kickass and easy to use blogging engine.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/natew/obtvse2/pull/14#issuecomment-25700492
> .

## 

Nate Wienert
natewienert.com @natebirdman http://twitter.com/natebirdman

**Comment by thatandyrose** [comment]
@natew cool makes sense, will do!

**Pull request closed without merging**
